version: '3'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - electionnet
      - authenticationnet

  redis:
    image: redis
    ports:
    - 6379:6379
    networks:
      - redisnet
networks:
  redisnet:
  electionnet:
  authenticationnet: